---
- name: Print env vars - TESTING ONLY
  hosts: all
  tasks:
  - name: print env
    ansible.builtin.command: printenv

  - name: Looking up end var
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"
