---
- name: Build and Push EE to registry
  hosts: all
  gather_facts: false
  vars:
    registry: adjsh.com
  tasks:
    - name: Make sure that podman is installed
      ansible.builtin.dnf:
        name:
          - podman
          - git
        state: present

    - name: Make sure that builder 3 is installed
      ansible.builtin.pip:
        name: ansible-builder>=3.0.0
        state: present

    - name: Set Directory Name with EE Tag
      ansible.builtin.set_fact:
        ee_tag: '{{ lookup("community.general.random_string", length=12, upper=false, special=false) }}'

    - name: Create Directory for EE-Build
      ansible.builtin.file:
        path: /var/ee-builds/{{ ee_tag }}
        state: directory

    - name: Print the working directory name
      ansible.builtin.debug:
        msg: using directory under /var/ee-builds/{{ ee_tag }}

    - name: Extracting the branch name from the webhook to be used as the ee image name
      ansible.builtin.set_fact:
        ee_name: "{{ tower_webhook_payload.ref.split('/')[-1] }}"

    - name: Git checkout the repo
      ansible.builtin.command:
        git clone -b {{ ee_name }} {{ tower_webhook_payload.repository.git_url }} /var/ee-builds/{{ ee_tag }}

    - name: Build the EE
      ansible.builtin.command:
        ansible-builder build -t {{ ee_name }}:{{ ee_tag }}

  # - name: Login to registry
  #   containers.podman.podman_login:
  #     username: "{{ controller_registry_username }}"
  #     password: "{{ controller_registry_password }}"
  #     registry: "{{ controller_registry_address }}"

  # - name: pull down the base images
  #   containers.podman.podman_image:
  #     username: "{{ controller_registry_username }}"
  #     password: "{{ controller_registry_password }}"
  #     name: "{{ base_image }}"
  #     pull: true
  #     state: present
  #     validate_certs: false


