---
- name: Linux Apply common config
  hosts: "{{ target_hosts }}"
  vars:
    target_hosts: "{{ new_vm_name if new_vm_name is defined else 'all' | default('all') }}"
  become: true
  roles:
  - rsoliman.linux_demos.linux_set_motd
  - rsoliman.linux_demos.linux_config_sysctl
  - geerlingguy.nginx