---
- name: build an EE
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /ee-build
      state: directory

  - name: template exec enc
    ansible.builtin.template:
      src: temp_execution-environmnet.yml.j2
      dest: /ee-build/execution-environmnet.yml

  - name: template reqs enc
    ansible.builtin.template:
      src: temp_requirements.yml.j2
      dest: /ee-build/requirements.yml

  - name: template python enc
    ansible.builtin.template:
      src: temp_requirements.txt.j2
      dest: /ee-build/requirements.txt

  - name: build image
    ansible.builtin.command: ansible-builder build -t dummy-ee:latest
    args:
      chdir: ee-build/