---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: update_result

- name: Check if a reboot is required
  ansible.builtin.stat:
    path:  /var/run/reboot-required
  register: file_stat
  changed_when: "{{ file_stat.stat.islnk is defined or (force_reboot is defined and force_reboot) }}"
  notify:
  - reboot_server
