---
- name: Ensure that URL is reachable from this host
  ansible.builtin.uri:
    url: "{{ protocol }}://{{ ansible_host }}:{{ endpoint_port }}/{{ endpoint }}"
    follow_redirects: none
    method: GET
    validate_certs: "{{ validate_certs | default(false) }}"
  register: _result
  until: _result.status == 200
  retries: 720
  delay: 5